development:
  adapter: sqlite3
  database: db/giga-blab_dev.sqlite3

test:
  adapter: sqlite3
  database: db/giga-blab_test.sqlite3

production:
  adapter: sqlite3
  database: db/giga-blab_live.sqlite3