defaults: &defaults
  adapter: mysql2
  username: ba86c479583555
  password: 2f406cb0
  host: localhost

development:
  <<: *defaults
  database: giga-blab_development

test:
  <<: *defaults
  database: giga-blab_development